### ISSUE TITLE
Stop working after one donwload

### ISSUE THREAD

**Issue by ken-huston** [white-glider/downloaded-files-virus-scan#1]
After one  download successfully scanned, in the following ones the program stop working.

At first, when I run `pstree -aT $(pgrep -x flock)` I get

```
flock -en /run/user/1000/scan-download.lock ...
  └─scan-download.s /home/prosal/bin/scan-download.sh
      └─inotifywait -qmr -e close_write -e moved_to /home/prosal/Descargas
```
but after the first analysis, the new result is: 

```
flock -en /run/user/1000/scan-download.lock ...
  └─scan-download.s /home/prosal/bin/scan-download.sh
```
It seem that inotifywait stop working.

**Comment by white-glider** [comment]
Hi @ken-huston. Thanks for reporting it.
Please, can you give more information about your system (e.g. Linux distro and version, platform, kernel version, etc.)?

**Comment by white-glider** [comment]
I could reproduce the same behavior here. It seems that `inotifywait -m` is not working as it should.
