### ISSUE TITLE
Doesnt scan when downloading files with google chrome on ubuntu 20.04

### ISSUE THREAD

**Issue by MandiYang** [white-glider/downloaded-files-virus-scan#2]
When i download eicar.com test file it doest detect when i use google chrome but when i use wget it worked.

**Comment by white-glider** [comment]
Hi @MandiYang. Thanks for reporting this.
Please, did you check if the processes are running? You can do that by executing `pstree -aT $(pgrep -x flock)`.
If the output is like the one described in the README here then please check where chrome is configured to save downloaded files.
This script monitors only one directory (~/Downloads) so if your browser is downloading files into a different directory then this script is not going to catch them.

**Comment by MandiYang** [comment]
i checked the process `pstree -aT $(pgrep -x flock)` after download with chrome , output:

    flock -en /run/user/1000/scan-download.lock ...
    └─scan-download.s /home/me/bin/scan-download.sh

**Comment by white-glider** [comment]
Please can you confirm which directory your Chrome is downloading files into?

**Comment by MandiYang** [comment]
I downloaded in the Downloads directory in my home.

**Comment by white-glider** [comment]
Closed as a duplicate of [this](https://github.com/white-glider/downloaded-files-virus-scan/issues/1) issue.
